src/core/urls.py
from django.urls import path
from core.views import (
    Homeview,
    CheckoutView,
    ItemDetailView,
    add_to_cart,
    remove_from_cart,
    OrderSummaryView,
    remove_item_from_cart,)

app_name = 'core'

urlpatterns = [
    path('', Homeview.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('products/<slug>/', ItemDetailView.as_view(), name='products'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('add_to_cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('remove_item_from_cart/<slug>/', remove_item_from_cart, name='remove_item_from_cart'),
]

src/projectname/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

src/core/models.py
from django.db import models
from django.conf import settings
from django_countries.fields import CountryField
from django.shortcuts import reverse

# Create your models here.

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

CATEGORY_CHOICES = (
    ('S', 'Shirts'),
    ('TS', 'T-Shirts'),
    ('OW', 'Out Sports'),
)

LABELS = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

PAYMENT_OPTIONS = (
    ('P', 'PayPal'),
    ('D', 'Debit Card'),
    ('C', 'Credit Card'),
)


class Item(models.Model):
    title = models.CharField(max_length=120)
    price = models.FloatField()
    category = models.CharField(choices=CATEGORY_CHOICES,
                                max_length=2,
                                default='S')
    labels = models.CharField(choices=LABELS,
                              max_length=1,
                              default='P')
    slug = models.SlugField()
    discount_price = models.FloatField(blank=True)
    description = models.TextField(max_length=300)
    image = models.ImageField()

    class Meta:
        pass

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("core:products", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart(self):
        return reverse("core:add_to_cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart(self):
        return reverse("core:remove_from_cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, )
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False, )

    class Meta:
        pass

    def __str__(self):
        return f"{self.item}"

    def get_total_value(self):
        return self.quantity * self.item.price

    def get_discount_value(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_value() - self.get_discount_value()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_discount_value()
        else:
            return self.get_total_value()


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street = models.CharField(max_length=120)
    landmark = models.CharField(max_length=120, blank=True, null=True)
    country = CountryField(multiple=False)
    zip = models.IntegerField()

    class Meta:
        pass

    def __str__(self):
        return self.user.username


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False, )
    billing_address = models.ForeignKey(BillingAddress, on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        pass

    def __str__(self):
        return f"{self.user.username}  {self.ordered_date}"

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

src/core/forms.py
from django import forms
from django.forms import ChoiceField
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


PAYMENT_OPTIONS = (
    ('P', 'PayPal'),
    ('D', 'Debit Card'),
    ('C', 'Credit Card'),
)


class CheckoutForm(forms.Form):
    street = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '1234 Main St',
        'class': 'form-control',
    }), max_length=120)
    landmark = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '1234 Main St',
        'class': 'form-control',
    }), max_length=120, required=False)
    country = CountryField(blank_label='Select Country').formfield(
        widget=CountrySelectWidget(attrs={
            'class': "custom-select d-block w-100",
            # 'id': "country"
        },)
    )
    zip = forms.IntegerField(widget=forms.TextInput(attrs={
        'placeholder': '123456',
        'class': 'form-control',
    }), )
    same_bill_address = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    save_info = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    payment_option = forms.ChoiceField(choices=PAYMENT_OPTIONS, widget=forms.RadioSelect())

src/core/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import TemplateView, ListView, DetailView, View
from core.models import Item, Order, OrderItem
from django.shortcuts import redirect, get_object_or_404
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from core.forms import CheckoutForm


# Create your views here.


class Homeview(ListView):
    paginate_by = 2
    template_name = 'core/home-page.html'
    model = Item
    context_object_name = 'items'
    extra_context = {
        'title': 'Products',
    }


class ItemDetailView(DetailView):
    model = Item
    template_name = 'core/product.html'


class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            return render(self.request, 'core/ordersummary.html',
                          context={'object': order})
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have any item in cart")
            return redirect('/')

    model = Order
    template_name = 'core/ordersummary.html'


class CheckoutView(View):
    def get(self, *args, **kwargs):
        form = CheckoutForm()
        context = {
            'form': form,
        }
        return render(self.request, 'core/checkout-page.html', context=context)

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        if form.is_valid():
            street = form.cleaned_data['street']
            landmark = form.cleaned_data['landmark']
            country = form.cleaned_data['country']
            zip = form.cleaned_data['zip']
            same_bill_address = form.cleaned_data['same_bill_address']
            save_info = form.cleaned_data['save_info']
            payment_option = form.cleaned_data['payment_option']
            print(street,
landmark,
country,
zip,
same_bill_address,
save_info,
payment_option)
        return redirect("core:checkout")


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False,
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity updated")
            return redirect('core:order-summary')
        else:
            messages.info(request, "This item added to your cart")
            order.items.add(order_item)
            return redirect('core:order-summary')
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user,
                                     ordered_date=ordered_date)
        order.items.add(order_item)
        messages.success(request, "This item added to your cart")
    return redirect('core:order-summary')


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user,
                                    ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.get(
                item=item,
                user=request.user,
                ordered=False,
            )
            order.items.remove(order_item)
            messages.success(request, "This item is removed from your cart")
            return redirect('core:order-summary')
        else:
            messages.warning(request, "This item is not in your cart")
            return redirect("core:products", slug=slug)
    else:
        messages.error(request, "You do not have an active order.")
        return redirect('core:order-summary')


@login_required
def remove_item_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user,
                                    ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.get(
                item=item,
                user=request.user,
                ordered=False,
            )
            print(order_item.quantity)
            if order_item.quantity <= 1:
                order.items.remove(order_item)
            else:
                order_item.quantity -= 1
                order_item.save()
            messages.success(request, "This item is removed from your cart")
            return redirect('core:order-summary')
        else:
            messages.warning(request, "This item is not in your cart")
            return redirect("core:order-summary")
    else:
        messages.error(request, "You do not have an active order.")
        return redirect('core:order-summary')

src/templates/core/home-page.html
{% extends 'core/base.html' %}

{% block content %}

    <!--Carousel Wrapper-->
    <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

        <!--Indicators-->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-1z" data-slide-to="1"></li>
            <li data-target="#carousel-example-1z" data-slide-to="2"></li>
        </ol>
        <!--/.Indicators-->

        <!--Slides-->
        <div class="carousel-inner" role="listbox">
            <!--First slide-->
            <div class="carousel-item active">
                <div class="view"
                     style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

                    <!-- Mask & flexbox options-->
                    <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

                        <!-- Content -->
                        <div class="text-center white-text mx-5 wow fadeIn">
                            <h1 class="mb-4">
                                <strong>Learn Bootstrap 4 with MDB</strong>
                            </h1>

                            <p>
                                <strong>Best & free guide of responsive web design</strong>
                            </p>

                            <p class="mb-4 d-none d-md-block">
                                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000
                                    users. Video and
                                    written versions
                                    available. Create your own, stunning website.</strong>
                            </p>

                            {#              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start#}
                            {#                free tutorial#}
                            {#                <i class="fas fa-graduation-cap ml-2"></i>#}
                            {#              </a>#}
                        </div>
                        <!-- Content -->

                    </div>
                    <!-- Mask & flexbox options-->

                </div>
            </div>
            <!--/First slide-->
            <!--Second slide-->
            <div class="carousel-item">
                <div class="view"
                     style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

                    <!-- Mask & flexbox options-->
                    <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

                        <!-- Content -->
                        <div class="text-center white-text mx-5 wow fadeIn">
                            <h1 class="mb-4">
                                <strong>Learn Bootstrap 4 with MDB</strong>
                            </h1>

                            <p>
                                <strong>Best & free guide of responsive web design</strong>
                            </p>

                            <p class="mb-4 d-none d-md-block">
                                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000
                                    users. Video and
                                    written versions
                                    available. Create your own, stunning website.</strong>
                            </p>

                        </div>
                        <!-- Content -->

                    </div>
                    <!-- Mask & flexbox options-->

                </div>
            </div>
            <!--/Second slide-->
            <!--Third slide-->
            <div class="carousel-item">
                <div class="view"
                     style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

                    <!-- Mask & flexbox options-->
                    <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

                        <!-- Content -->
                        <div class="text-center white-text mx-5 wow fadeIn">
                            <h1 class="mb-4">
                                <strong>Learn Bootstrap 4 with MDB</strong>
                            </h1>

                            <p>
                                <strong>Best & free guide of responsive web design</strong>
                            </p>

                            <p class="mb-4 d-none d-md-block">
                                <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000
                                    users. Video and
                                    written versions
                                    available. Create your own, stunning website.</strong>
                            </p>

                        </div>
                        <!-- Content -->

                    </div>
                    <!-- Mask & flexbox options-->

                </div>
            </div>
            <!--/Third slide-->

        </div>
        <!--/.Slides-->

        <!--Controls-->
        <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
        <!--/.Controls-->

    </div>
    <!--/.Carousel Wrapper-->
    <div class="container">

        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

            <!-- Navbar brand -->
            <span class="navbar-brand">Categories:</span>

            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="basicExampleNav">

                <!-- Links -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">All
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Shirts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Sport wears</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Outwears</a>
                    </li>

                </ul>
                <!-- Links -->

                <form class="form-inline">
                    <div class="md-form my-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    </div>
                </form>
            </div>
            <!-- Collapsible content -->

        </nav>
        <!--/.Navbar-->

        <section class="text-center mb-4">

            <div class="row wow fadeIn">
                {% for product in items %}
                    <div class="col-lg-3 col-md-6 mb-4">

                        <div class="card">

                            <!--Card image-->
                            <div class="view overlay">
                                <img src="{{ product.image.url }}" class="card-img-top" alt="sccs">
                                <a href="{{ product.get_absolute_url }}">
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>

                            <div class="card-body text-center">
                                <h5 class="grey-text">{{ product.get_category_display }}</h5>
                                <h5>
                                    <strong>
                                        <a href="{{ product.get_absolute_url }}"
                                           class="dark-grey-text">{{ product.title }}
                                            <span class="badge badge-pill {{ product.get_labels_display }}-color">{{ product.labels }}</span>
                                        </a>
                                    </strong>
                                </h5>

                                <h4 class="font-weight-bold blue-text">
                                    {% if product.discount_price %}
                                        <strong>${{ product.discount_price }}</strong>
                                    {% else %}
                                        <strong>${{ product.price }}</strong>
                                    {% endif %}
                                </h4>

                            </div>
                            <!--Card content-->

                        </div>
                        <!--Card-->

                    </div>
                {% endfor %}
            </div>

        </section>
        <!--Section: Products v.3-->
    {% if is_paginated %}{% include 'core/pagination.html' %}
    {% endif %}
    </div>
{% endblock %}

src/templates/core/item_list.html
{% extends 'core/base.html' %}
{% block content %}
    <p>Something goes here</p>
{% endblock %}

src/templates/core/navbar.html
{% load cart_template_tags %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <a class="navbar-brand waves-effect" href="{% url "core:home" %}">
            <strong class="blue-text">LOGO</strong>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <span class="navbar-nav mr-auto"></span>
            <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'core:order-summary' %}"class="nav-link waves-effect">
                            <i class="fas fa-shopping-cart"></i>
                            <span class="badge badge-pill red fa-id-badge">{{ request.user|cart_item_count }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url "account_logout" %}" class="nav-link waves-effect">
                            {#              <span class=""></span>#}
                            <span class="fas fa-user"> Logout </span>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url "account_login" %}" class="nav-link waves-effect">
                            {#              <span class=""></span>#}
                            <span class="fas fa-user-alt"> Login </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url "account_signup" %}" class="nav-link waves-effect">
                            {#              <span class=""></span>#}
                            <span class="fas fa-sign-in-alt"> Sign up </span>
                        </a>
                    </li>
                    </ul>
                    </div>


                {% endif %}

    </div>
</nav>

src/templates/core/ordersummary.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block content %}
<div class="container">
    <section class="mt-5 pt-4">
        <h1>{% trans "Order Summary" %}</h1>
        <div >
                <table class="table tab">
                    <thead>
                        <tr>
                          <th scope="col"><strong>#</strong></th>
                          <th scope="col"><strong>Item Title</strong></th>
                          <th scope="col"><strong>Price </strong></th>
                          <th scope="col"><strong>Quantity</strong></th>
                          <th scope="col"><strong>Total Item Price</strong></th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for order_item in object.items.all %}
                        <tr class="light">
                          <td>{{ forloop.counter }}</td>
                          <td>{{ order_item.item.title }}</td>
                          <td>{{ order_item.item.price }}</td>
                          <td>
                              <a href="{% url 'core:remove_item_from_cart' order_item.item.slug %}"><span class="fas fa-minus mr-2"></span></a>
                              {{ order_item.quantity }}
                              <a href="{% url 'core:add_to_cart' order_item.item.slug %}"><span class="fas fa-plus ml-2"></span></a>
                          </td>
                          <td>
                                {% if order_item.item.discount_price %}
                                    {{ order_item.get_discount_value }}$
                                    <sup class="badge badge-default">saving {{ order_item.get_amount_saved }}$</sup>
                                {% else %}
                                    {{ order_item.get_total_value }}$
                            {% endif %}
                                <a href="{% url 'core:remove_from_cart' order_item.item.slug %}"><span class="fas fa-trash float-right" style="color: red"></span></a>
                          </td>
                        </tr>
                      {% empty %}
                          <tr>
                              <td colspan="5">You Do Not Have Any Item In Cart!</td>
                          </tr>
                      {% endfor %}
                      {% if object.get_total %}
                        <tr>
                          <td colspan="4"><b>Total : </b></td>
                          <td>
                              {{ object.get_total }}$
                          </td>
                        </tr>
                          <tr>
                              <td colspan="2">
                                  <a href="{% url 'core:checkout' %}" class="btn btn-warning">Checkout</a>
                              </td>
                              <td colspan="3">
                                  <a href="{% url 'core:home' %}" class="btn btn-default float-right">Continue</a>
                              </td>
                          </tr>
                          {% else %}<tr>
                          <td colspan="5">
                            <a href="{% url 'core:home' %}" class="btn btn-default float-right">Continue Shopping</a>
                          </td>
                      </tr>
                      {% endif %}
                      </tbody>
                </table>
        </div>
    </section>
</div>
{% endblock %}

src/templates/core/product.html
{% extends 'core/base.html' %}


{% block content %}
    <!--Main layout-->
    <main class="mt-5 pt-4">
        <div class="container dark-grey-text mt-5">

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <img src="{{ object.image }}" class="img-fluid" alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <!--Content-->
                    <div class="p-4">

                        <div class="mb-3">
                            <a href="">
                                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
                            </a>

                        </div>



                        {% if object.discount_price %}
                            <p class="lead">
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
                                <span>${{ object.discount_price }}</span>
                            </p>
                        {% else %}
                            <p class="lead">
                                <span>${{ object.price }}</span>
                            </p>
                        {% endif %}
                        <p class="lead font-weight-bold">Description</p>

                        <p>{{ object.description | default:"nahi hai kuch" }}</p>
                        {##}
                        {#            <form class="d-flex justify-content-left">#}
                        {#              <!-- Default input -->#}
                        {#              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">#}
                        {#            </form>#}

                        <a href="{{ object.get_add_to_cart }}" class="btn btn-primary btn-md my-0 p">Add to cart
                            <i class="fas fa-shopping-cart ml-1"></i>
                        </a>
                        <a href="{{ object.get_remove_from_cart }}" class="btn btn-danger btn-md my-0 p">remove from
                            cart
                            <i class="fas fa-shopping-cart ml-1"></i>
                        </a>
                    </div>
                    <!--Content-->

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            <hr>

            <!--Grid row-->
            <div class="row d-flex justify-content-center wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 text-center">

                    <h4 class="my-4 h4">Additional information</h4>

                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta
                        odit
                        voluptates,
                        quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg"
                         class="img-fluid" alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg"
                         class="img-fluid" alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg"
                         class="img-fluid" alt="">

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

        </div>
    </main>
    <!--Main layout-->

{% endblock %}